#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions

runCase() {

  echo "Running $1 case"
  cd "$SCRIPT_DIR" || {
    echo "$SCRIPT_DIR does not exist"
    return
  }
  echo "Directory changed to $(pwd)"

  case=$1
  caseDir=microTGA${case}

  cp -r ./mircoTGATemplate/ "$caseDir"
  cp "${caseDir}"/constant/radiationProperties{"$case",}

  cd "$caseDir" || {
    echo "$caseDir does not exist"
    return
  }
  echo "Directory changed to $(pwd)"

  runApplication blockMesh
  runApplication setFields
  runApplication renumberMesh -overwrite
  runApplication checkMesh

  runApplication decomposePar

  runParallel $(getApplication)
}

main() {
  runCase MeanTemp
  runCase P1
}

[ "${BASH_SOURCE[0]}" = "${0}" ] && main
