[project]
name = "pgf-py-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Tadeusz Rymarz", email = "tdrym.dev@pm.me" }]
requires-python = ">=3.12"
dependencies = [
    "vtk>=9.5.2",
]

[project.scripts]
pgf-py-utils = "pgf_py_utils:main"

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"
