#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CASES_DIR="$SCRIPT_DIR/cases"

. "$SCRIPT_DIR/../utilities/bash_utils/helpers.sh"

if [[ ! -d "$CASES_DIR" ]]; then
  clog ERROR "cases does not exist: $CASES_DIR"
  exit 1
fi

shopt -s globstar nullglob
cleaned=0
failed=0

for clean_script in "$CASES_DIR"/**/Allclean "$CASES_DIR"/**/Allclean.sh; do
  case_dir="$(dirname "$clean_script")"
  case_name="${case_dir#"$CASES_DIR"/}"
  clog "Cleaning $case_name..."

  if (
    cd "$case_dir" && bash "$clean_script"
  ); then
    clog SUCCESS "$case_name cleaned"
  else
    clog ERROR "$case_name cleanup failed"
    failed=$((failed + 1))
  fi
  cleaned=$((cleaned + 1))
done

# These state directories are generated by the regression runner and are not
# consistently handled by the individual legacy cleanup scripts.
for state_dir in "$CASES_DIR"/**/.foamcli-state; do
  rm -rf "$state_dir"
done

rm -rf "$SCRIPT_DIR/simulation_logs" "$SCRIPT_DIR/.mock_bin"

if [[ "$failed" -ne 0 ]]; then
  clog ERROR "CleanAllCases finished: $cleaned cleaners run, $failed failed"
  exit 1
fi

clog SUCCESS "CleanAllCases finished: $cleaned cleaners run"
