#!/bin/bash

runCase() {

  case=$1
  caseDir=flatPlate${case}

  cp -r flatPlateTemplate "$caseDir"
  cp "${caseDir}"/constant/pyrolysisProperties${case,}
  cp "${caseDir}"/system/controlDict${case,}
  cp "${caseDir}"/system/setFieldsDict${case,}

  cd "$caseDir" || exit

  blockMesh
  setSet -batch makeFaceSet.setSet
  createPatch -overwrite
  setFields

  decomposePar

  mpirun -np 4 porousGasificationFoam -parallel
}

main() {
  runCase Cold
  runCase HotImmediate
  runCase Stat
}

[ "${BASH_SOURCE[0]}" = "${0}" ] && main
