#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions

runCase() {

  echo "Running $1 case"
  cd "$SCRIPT_DIR" || {
    echo "$SCRIPT_DIR does not exist"
    return
  }
  echo "Directory changed to $(pwd)"

  case=$1
  caseDir=flatPlate${case}

  cp -r flatPlateTemplate "$caseDir"
  cp "${caseDir}"/constant/pyrolysisProperties{"$case",}
  cp "${caseDir}"/system/controlDict{"$case",}
  cp "${caseDir}"/system/setFieldsDict{"$case",}

  cd "$caseDir" || {
    echo "$caseDir does not exist"
    return
  }
  echo "Directory changed to $(pwd)"

  runApplication blockMesh
  runApplication setSet -batch makeFaceSet.setSet
  runApplication createPatch -overwrite
  runApplication setFields

  runApplication decomposePar

  runParallel $(getApplication)
}

main() {
  runCase Cold
  runCase HotImmediate
  runCase Stat
}

[ "${BASH_SOURCE[0]}" = "${0}" ] && main
