#!/bin/bash
# Requires a Yade-enabled solver build: ./build.sh --yade

cp -r 0.orig 0
blockMesh   > /dev/null 2>&1
setFields   > /dev/null 2>&1
decomposePar > /dev/null 2>&1
mkdir -p spheres springs
mpirun --allow-run-as-root -n 2 yade MPI_lambda.py
