#!/bin/bash
cd "${0%/*}" || exit 1
. "${WM_PROJECT_DIR:?}/bin/tools/RunFunctions"

restore0Dir
runApplication blockMesh
runApplication setFields
runApplication setExprFields
runApplication $(getApplication)
